# Kitchen - switch blue LED-stripes on 30min after sunset / off 22:00 / daily
- alias: Blaue Küche An
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
    offset: "+00:30:00"
  action:
    service: switch.turn_on
    entity_id: switch.kuche_oben

- alias: Blaue Küche Aus
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: "22:00:28"
  action:
    service: switch.turn_off
    entity_id: switch.kuche_oben
