homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric  
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

sun:
discovery:
updater:
  include_used_components: true
introduction:
frontend:
config:
history:
logbook:
conversation:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Weather prediction
sensor:


# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
