homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric  
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

binary_sensor:
  - platform: workday
    country: DE
    province: NW
config:
conversation:
device_tracker:
  - platform: owntracks
  - platform: mqtt
    devices:
      Nexus6: /owntracks
discovery:
frontend:
history:
  exclude:
    entities:
      - sensor.average_load_5m
      - sensor.disk_use_
      - sensor.last_boot
      - sensor.ram_use
      - sensor.since_last_boot
      - sensor.swap_use
http:
  #api_password: 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
# introduction:
light:
  - platform: hue
    host: !secret hue_ip
logbook:
  exclude:
    entities:
      - sensor.average_load_5m
      - sensor.disk_use_
      - sensor.last_boot
      - sensor.ram_use
      - sensor.since_last_boot
      - sensor.swap_use
mqtt:
recorder:
  purge_days: 7
sun:
tradfri:
  host: !secret tradfri_ip
  api_key: !secret tradfri_api_key
tts:
  - platform: google
updater:
  include_used_components: true

  
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_networkkey
  
sensor: !include_dir_merge_list sensors/

group: !include_dir_merge_named group
automation: !include automations.yaml
script: !include scripts.yaml
