homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric  
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
conversation:
device_tracker:
  - platform: owntracks
  - platform: mqtt
    devices:
      Nexus6: /owntracks
discovery:
frontend:
history:
  exclude:
    entities:
      - sensor.average_load_5m
      - sensor.disk_use_
      - sensor.last_boot
      - sensor.ram_use
      - sensor.since_last_boot
      - sensor.swap_use
http:
  #api_password: 
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
# introduction:
logbook:
  exclude:
    entities:
      - sensor.average_load_5m
      - sensor.disk_use_
      - sensor.last_boot
      - sensor.ram_use
      - sensor.since_last_boot
      - sensor.swap_use
mqtt:
sun:
tts:
  - platform: google
updater:
  include_used_components: true

  

sensor: !include_dir_merge_list sensors/

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
