- platform: fritzbox_callmonitor
  host: !secret fritzboxsu_ip
  username: !secret fritzboxsu_id
  password: !secret fritzboxsu_pw
  prefixes:
    - '+49'
    
- platform: fritzbox_netmonitor
  host: !secret fritzboxsu_ip