- platform: systemmonitor
  resources:
    - type: last_boot
    - type: since_last_boot
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: swap_use_percent
    - type: load_5m