# https://home-assistant.io/components/sensor.template/
# https://home-assistant.io/docs/configuration/templating/
# https://community.home-assistant.io/t/get-a-specific-attributes-on-an-entity/1441
#
#
- platform: template
  sensors:
    fritzkuchemitte:
      friendly_name: "Küche Mitte"
      unit_of_measurement: "Watt"
      value_template: "{{ states.switch.kuche_mitte.attributes.current_consumption }}"
