homeassistant:
  customize:

    sensor.pihole_ads_percentage_blocked_today:
      friendly_name: Percentage of Ad Traffic Blocked
      unit_of_measurement: '%'
      icon: mdi:ticket-percent

    sensor.pihole_dns_queries_today:
      friendly_name: DNS Queries Today
      icon: mdi:note-text

    sensor.pihole_dns_unique_domains:
      friendly_name: Unique Domains
      icon: mdi:approval

group:
  Pi Hole:
    entities:
      - sensor.pihole_dns_queries_today
      - sensor.pihole_ads_percentage_blocked_today
      - sensor.pihole_dns_unique_domains

sensor:
  - platform: pi_hole
    host: !secret pihole_ip
    monitored_conditions:
      - ads_percentage_today
      - unique_domains
      - dns_queries_today
