homeassistant:
  customize:

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - pressure
      - precipitation
      - windSpeed
      
  - platform: dwd_weather_warnings
    region_name: !secret home_region
