homeassistant:     
  customize:
sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - pressure
      - precipitation
      - windSpeed
      - humidity
      
  - platform: dwd_weather_warnings
    region_name: !secret home_region

  - platform: darksky
    api_key: !secret darksky_api
    monitored_conditions:
      - temperature
      - pressure
      - precip_intensity
      - wind_speed
      - humidity
      - icon
      - nearest_storm_distance
      - precip_type
      - ozone
      - temperature_max
      - temperature_min
      - visibility
      - hourly_summary
    update_interval:
      minutes: 5
